name: Push Notification

on:
  push:
    branches: [ main ]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get commit info
        id: commit-info
        run: |
          echo "message=$(git log --format=%B -n 1 ${{ github.sha }})" >> $GITHUB_OUTPUT
          echo "author_name=$(git log --format=%an -n 1 ${{ github.sha }})" >> $GITHUB_OUTPUT
          echo "files_changed=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | tr '\n' ', ')" >> $GITHUB_OUTPUT
          
          # Extract issue numbers from commit message
          ISSUE_PATTERN='(fix|close|resolve|fixes|closes|resolves|fixed|closed|resolved) #([0-9]+)'
          ISSUE_NUMBERS=$(echo "${{ github.event.head_commit.message }}" | grep -oE "$ISSUE_PATTERN" | grep -oE '#[0-9]+' | tr -d '#' || echo "")
          echo "issue_numbers=$ISSUE_NUMBERS" >> $GITHUB_OUTPUT

      - name: Send GitHub app notification
        run: |
          echo "🔔 New Push to Repository"
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"
          echo "Author: ${{ steps.commit-info.outputs.author_name }}"
          echo "Message: ${{ steps.commit-info.outputs.message }}"
          
          # Create a repository dispatch event for external notification systems
          # This allows other systems to react to all pushes
          TOKEN="${{ secrets.GITHUB_TOKEN }}"
          REPO="${{ github.repository }}"
          curl -X POST \
            -H "Authorization: token $TOKEN" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            "https://api.github.com/repos/$REPO/dispatches" \
            -d "{\"event_type\":\"push_event\",\"client_payload\":{\"ref\":\"${{ github.ref }}\",\"sha\":\"${{ github.sha }}\",\"author\":\"${{ steps.commit-info.outputs.author_name }}\"}}"

      - name: Comment on related issues
        if: ${{ steps.commit-info.outputs.issue_numbers != '' }}
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ steps.commit-info.outputs.issue_numbers }}
          body: |
            ## 🔔 This issue was referenced in a commit
            
            **Branch:** ${{ github.ref_name }}
            **Commit:** [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }})
            **Author:** ${{ steps.commit-info.outputs.author_name }}
            
            ### Commit Message
            ```
            ${{ steps.commit-info.outputs.message }}
            ```
            
            ### Files Changed
            ```
            ${{ steps.commit-info.outputs.files_changed }}
            ```
            
            [View Changes](https://github.com/${{ github.repository }}/commit/${{ github.sha }})